server:
  port: 8099

spring:
  application:
    name: like-post

  datasource:
    url: jdbc:mysql://localhost:3306/likepostdb
    username: root
    password: 123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
  devtools:
    livereload:
      port: 35730
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yousuf.ahmad.saleh@gmail.com
    password: AhmadSaleh/70
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
